# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
promptToReturnFromSubprocess: false
git:
  diffRenderers:
    - colorArg: always
      useConfig: true
      type: rawGit
gui:
  skipDiscardChangeWarning: true
  showNumstatInFilesView: true
  showRandomTip: true
  showBottomLine: true
  nerdFontsVersion: "3"
  showFileIcons: true
  showDivergenceFromBaseBranch: arrowAndNumber
  filterMode: fuzzy
