#!/bin/sh

GIT_ROOT="$(git rev-parse --show-toplevel)"
red='\033[0;31m'

exec 1>&2

#
# Blacklist the lazy-lock.json file off main
#
branch="$(git rev-parse --abbrev-ref HEAD)"
blacklistFile="nvim/lazy-lock.json"

if [ "$branch" != "main" ]; then
	if git diff --cached --name-only HEAD |
		grep --quiet --line-regexp --fixed-strings "$blacklistFile"; then
		echo "${red}################################"
		echo "${red}ERROR: "
		echo "${red}Cannot change $blacklistFile when not on branch main. Aborting commit..."
		echo "${red}Unstage $blacklistFile to commit."
		echo "${red}################################"
		exit 1
	fi
fi
