#!/bin/sh

GIT_ROOT="$(git rev-parse --show-toplevel)"
red='\033[0;31m'

exec 1>&2

#
# Blacklist the lazy-lock.json file off main
#
# if [ "$(git diff --exit-code -- $blacklistFile)" == "1" ]; then
branch="$(git rev-parse --abrev-ref HEAD)"
blacklistFile="nvim/LazyVim/lazy-lock.json"

if [ "$branch" != "main" ]; then
	if git diff --cached --name-only HEAD | grep --quiet --line-regexp --fixed-strings "$blacklistFile"; then
		echo "${red}################################"
		echo "${red}ERROR: "
		echo "${red}Cannot change $blacklistFile when not on branch main. Aborting commit..."
		echo "${red}Unstage $blacklistFile to commit."
		echo "${red}################################"
		exit 1
	else
		echo "Did not block edits"
	fi
fi
