# Symlink this file to ~/.tmux.conf

# set -g status-right "Hello, tmux.conf"

# Make <ESC> process instantly in nvim
set -g escape-time 0

# Enable mouse support
set -g mouse on

# bind-key y display-popup -w 100% -h 70% -E 'comm -23 <(tmux list-keys | sort) <(tmux -L test -f /dev/null list-keys | sort) | cut -c-"$(tput cols)" | fzf -e -i --prompt="tmux hotkeys: " --info=inline --layout=reverse --scroll-off=5 --tiebreak=index --header "prefix=yes-prefix root=no-prefix" > /dev/null'
